# Ejercicios básicos para python 

<img src = 'EjBa.png'>

## Resolución


### 1.


In [ ]:
x = int(input('Ingrese el numero que desea analizar: \n'))

if x%2 == 0:
    print("El numero ingresado es par")
else:
    print("El numero ingresado es impar")

### 2.

In [11]:
x = input('Ingrese el numero de filas y columnas separadas por un espacio:\n').split(" ")
Filas = int(x[0])
Columnas = int(x[1])
import numpy as np

Matriz = np.zeros((Filas, Columnas))
for j in range(Filas):
    for k in range(Columnas): 
        if j%2 ==0:
            Matriz[j,k] = 1

print(Matriz)

Ingrese el numero de filas y columnas separadas por un espacio:
7 9
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 3.

In [25]:
x = list(int(i) for i in input('Ingrese el vector separando los elementos por comas:\n').split(","))

Max = -1000
Min = 1000

for i in x:
    if i>Max:
        Max = i
    if i<Min:
        Min = i

print('El minimo valor encontrado fue: ',Min,', y el maximo valor encontrado fue: ', Max)

Ingrese el vector separando los elementos por comas:
5,6,4,2,3,9
El minimo valor encontrado fue:  2 , y el maximo valor encontrado fue:  9


### 4.

In [32]:
x = input('Ingrese vector: \n').split(',')
Vector = []
for i in x:
    Vector.append(int(i))
Numero = int(input('Ingrese Numero:\n'))

for i in Vector:
    if Numero == i:
        print('El numero deseado se encuentra en el vector ingresado')

Ingrese vector: 
5,6,4,2,3,9
Ingrese Numero:
5
El numero deseado se encuentra en el vector ingresado


### 5.

In [13]:
x = input('Ingrese matriz separando las filas por ; y las columnas por ,: \n').split(';')
x = list(i.split(',') for i in x)
Numero = int(input('Ingrese numero: \n'))

Cuenta = 0
for i in range(len(x)):
    for j in range(len(x[0])):
        x[i][j] = int(x[i][j])
        if x[i][j] == Numero:
            Cuenta = Cuenta +1
print('La cantidad de veces que aparece el numero en la matriz es : ',Cuenta)

Ingrese matriz separando las filas por ; y las columnas por ,: 
1,2,3;3,6,5;7,9,3
Ingrese numero: 
7
La cantidad de veces que aparece el numero en la matriz es :  1


### 6.

In [26]:
x = input('Ingrese una Matriz y un numero, separados por espacio').split(" ")
Numero = int(x[1])
Matriz = list(list(int(i) for i in j.split(',')) for j in x[0].split(';'))
Cuenta = 0
for i in range(len(Matriz)):
    aux = 0
    for j in range(len(Matriz[0])):
        if Matriz[i][j] == Numero:
            aux +=1
    if aux >0:
        Cuenta +=1
print('El numero de filas que contienen el numero ingresado en la matriz es: ', Cuenta)        

Ingrese una Matriz y un numero, separados por espacio1,2,3;3,3,5;7,9,9 3
El numero de filas que contienen el numero ingresado en la matriz es:  2
